### PR TITLE
[add/path-to-connection-uri] Update Transport.php

### PR DESCRIPTION
**Pull request by mikevrind**
Add the path, which could be configured in the hosts, to the request uri.

 See https://github.com/elastic/elasticsearch-php/issues/1377 for more details.

_Please note that there isn't a 8.7 branch on this repository while there is a 8.7. release._

### CODE REVIEW

**Comment by ezimuel** [comment]
@mikevrind thanks for PR! Can I ask to send it against `main` branch? I need to cleanup the old branches. Thanks.

**Comment by mikevrind** [comment]
@ezimuel I created https://github.com/elastic/elastic-transport-php/pull/21

**Comment by sh3bang** [comment]
The rest path should be appended (!) to proxy-server path and not overwrite!

https://github.com/elastic/elastic-transport-php/pull/19/commits/966f4463c9eaeb5a7274f761e333bb0d35f34cf4

**Comment by ezimuel** [comment]
> @mikevrind Wrong! The REST path should be appended (!) to proxy-server path and not be overwritten!
> 
> [966f446](https://github.com/elastic/elastic-transport-php/commit/966f4463c9eaeb5a7274f761e333bb0d35f34cf4)

@sh3bang why do you think this is wrong? The `setupConnectionUri()` is executed only if a request does not have an host specified, so we can override it. The default host is specified using the `TransportBuilder::setHosts()`.

**Comment by ezimuel** [comment]
@mikevrind you right, we need to preserve the existing path of the request, otherwise the path of the endpoints will be missing. I'm preparing a fix for this in #21. Thanks!

**Comment by sh3bang** [comment]
you can do it safety even with one line - but not matter, it works. thanks.

**Pull request closed without merging**
